# Generated by packaging/homebrew/render.sh — do not edit by hand.
cask "aide-app" do
  version "0.3.3"
  sha256 "7802449464147ba2466348e0005ba496418c4ed3b1b1dee461f82a8a523064f4"

  url "https://github.com/matheus-meneses/aide/releases/download/v0.3.3/Aide-#{version}.dmg"
  name "Aide"
  desc "Personal work assistant desktop app"
  homepage "https://github.com/matheus-meneses/aide"

  app "Aide.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Aide.app"],
                   sudo: false
  end

  caveats <<~CAVEATS
    Aide.app is not notarized by Apple. This cask removes the quarantine
    attribute on install so it launches normally. If macOS still blocks it,
    right-click the app and choose Open the first time.
  CAVEATS

  zap trash: [
    "~/.aide",
    "~/Library/Application Support/Aide",
  ]
end
