# Generated by packaging/homebrew/render.sh — do not edit by hand.
cask "aide-app" do
  version "0.4.0"
  sha256 "2e5e65da272ce0647922d069adda2c8e40bb17331d8b86abdd13045753d44db4"

  url "https://github.com/matheus-meneses/aide/releases/download/v0.4.0/Aide-#{version}.dmg"
  name "Aide"
  desc "Personal work assistant desktop app"
  homepage "https://github.com/matheus-meneses/aide"

  app "Aide.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Aide.app"],
                   sudo: false
  end

  caveats <<~CAVEATS
    Aide.app is not notarized by Apple. This cask removes the quarantine
    attribute on install so it launches normally. If macOS still blocks it,
    right-click the app and choose Open the first time.
  CAVEATS

  zap trash: [
    "~/.aide",
    "~/Library/Application Support/Aide",
  ]
end
