# Generated by packaging/homebrew/render.sh — do not edit by hand.
cask "aide" do
  version "0.2.0-rc.2"
  sha256 "7807bd73549ebc309e458ae2a17b3b43e951ccd0b671c0f0d82f074b36655451"

  url "https://github.com/matheus-meneses/aide/releases/download/v0.2.0-rc.2/Aide-#{version}.dmg"
  name "Aide"
  desc "Personal work assistant desktop app"
  homepage "https://github.com/matheus-meneses/aide"

  app "Aide.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Aide.app"],
                   sudo: false
  end

  caveats <<~CAVEATS
    Aide.app is not notarized by Apple. This cask removes the quarantine
    attribute on install so it launches normally. If macOS still blocks it,
    right-click the app and choose Open the first time.
  CAVEATS

  zap trash: [
    "~/.aide",
    "~/Library/Application Support/Aide",
  ]
end
