# Generated by packaging/homebrew/render.sh — do not edit by hand.
cask "aide" do
  version "0.3.2"
  sha256 "8a98798824cd6ece6936db8d3f6b7d735d428c027695d3f90bb0126ae53fbd34"

  url "https://github.com/matheus-meneses/aide/releases/download/v0.3.2/Aide-#{version}.dmg"
  name "Aide"
  desc "Personal work assistant desktop app"
  homepage "https://github.com/matheus-meneses/aide"

  app "Aide.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Aide.app"],
                   sudo: false
  end

  caveats <<~CAVEATS
    Aide.app is not notarized by Apple. This cask removes the quarantine
    attribute on install so it launches normally. If macOS still blocks it,
    right-click the app and choose Open the first time.
  CAVEATS

  zap trash: [
    "~/.aide",
    "~/Library/Application Support/Aide",
  ]
end
