# Generated by packaging/homebrew/render.sh — do not edit by hand.
class Aide < Formula
  desc "Personal work assistant CLI"
  homepage "https://github.com/matheus-meneses/aide"
  version "0.3.2"
  license "BUSL-1.1"

  on_macos do
    on_arm do
      url "https://github.com/matheus-meneses/aide/releases/download/v0.3.2/aide_darwin_arm64"
      sha256 "d075c625f8b29f560300d696d32e96602be9ac9d51188d180d4ababa75da2b18"
    end
    on_intel do
      url "https://github.com/matheus-meneses/aide/releases/download/v0.3.2/aide_darwin_amd64"
      sha256 "39319ad8f4ae57484ff10f33a52857b6a9ca702acc4541b990a3b9c9c1ca7203"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/matheus-meneses/aide/releases/download/v0.3.2/aide_linux_arm64"
      sha256 "b8178536576dae4e3be545952bb13ad373b4f123f19989a9eae5f3120611da2d"
    end
    on_intel do
      url "https://github.com/matheus-meneses/aide/releases/download/v0.3.2/aide_linux_amd64"
      sha256 "5ad0557b02fbea6e5f0df83a6d896242b6e85961f7f3a499a53a1afb6fabc160"
    end
  end

  def install
    bin.install Dir["aide_*"].first => "aide"
    chmod 0555, bin/"aide"
    generate_completions_from_executable(bin/"aide", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aide version")
  end
end
